export enum VersionGeneration {
  I = "generation-i",
  II = "generation-ii",
  III = "generation-iii",
  IV = "generation-iv",
  V = "generation-v",
  VI = "generation-vi",
  VII = "generation-vii",
  VIII = "generation-viii",
}

export enum VersionGenerationGroup {
  RedBlue = "red-blue",
  Yellow = "yellow",
  Crystal = "crystal",
  Gold = "gold",
  Silver = "silver",
  Emerald = "emerald",
  FireredLeafgreen = "firered-leafgreen",
  RubySapphire = "ruby-sapphire",
  DiamondPearl = "diamond-pearl",
  HeartgoldSoulsilver = "heartgold-soulsilver",
  Platinum = "platinum",
  BlackWhite = "black-white",
  Animated = "animated",
  OmegarubyAlphasapphire = "omegaruby-alphasapphire",
  XY = "x-y",
  Icons = "icons",
  UltraSunUltraMoon = "ultra-sun-ultra-moon",
}
